wip

diff --git a/cix_upgrade b/cix_upgrade
--- a/cix_upgrade
+++ b/cix_upgrade
@@ -56,9 +56,6 @@ upgrade_packages()
 				/root/bin/upgrade.sh start
 			fi
 
-#			[ -r /var/spool/myb/state.conf ] && ${RM_CMD} -f /var/spool/myb/state.conf
-#			[ -r /var/spool/myb/last_result.txt ] && ${RM_CMD} -f /var/spool/myb/last_result.txt
-
 			if [ "${mod_cbsd_queue_enabled}" = "YES" -a -z "${MOD_CBSD_QUEUE_DISABLED}" ]; then
 				if [ -z "${cbsd_queue_backend}" ]; then
 					MOD_CBSD_QUEUE_DISABLED="1"
@@ -97,8 +94,8 @@ list_packages()
 	PATH="${OPATH}"
 
 	if [ ${save_repo} -eq 1 ]; then
-		STD_OUT="/tmp/clonos_ver.conf"
-		STD_OUT_JSON="/tmp/clonos_ver.json"
+		STD_OUT="/tmp/cix_upgrade.conf"
+		STD_OUT_JSON="/tmp/cix_upgrade.conf.json"
 		${TRUNCATE_CMD} -s0 ${STD_OUT} ${STD_OUT_JSON}
 	fi
 
@@ -214,19 +211,14 @@ EOF
 json=0
 save_repo=0
 
-cache_file="/tmp/clonos_ver2.conf"
+cache_file="/tmp/cix_upgrade_latest.conf"
 
 case "${mode}" in
 	list)
 		list_packages
 		;;
-	listjson)
-		cache_file="/tmp/clonos_ver2.conf"
-		json=1
-		list_packages
-		;;
-	listjson2)
-		cache_file="/tmp/clonos_ver2.conf"
+	listjson|listjson2)
+		cache_file="/tmp/cix_upgrade_latest.conf"
 		json=1
 		list_packages
 		;;
@@ -234,9 +226,20 @@ case "${mode}" in
 		dryrun=0
 		upgrade_packages
 		;;
+#	check_upgrade)
+#		dryrun=1
+#		upgrade_packages
+#		;;
 	check_upgrade)
-		dryrun=1
-		upgrade_packages
+		URL="https://clonos-pkg.convectix.com/FreeBSD:13:amd64/latest/clonos_ver.conf"
+		_res=$( timeout 10 ${FETCH_CMD} -o ${cache_file} ${URL} 2>&1 )
+		ret=$?
+		if [ ${ret} -eq 0 ]; then
+			echo "done"
+		else
+			${RM_CMD} -f ${cache_file}
+			err 1 "Error: ${_res}"
+		fi
 		;;
 	repo)
 		json=1
